# NthLayer Deployment Gate - GitLab CI Template
#
# Include this template in your .gitlab-ci.yml:
#   include:
#     - local: '.nthlayer-gate.yml'
#
# Then use the template in your pipeline:
#   deploy:
#     extends: .nthlayer-gate
#     variables:
#       SERVICE_FILE: services/my-service.yaml
#     script:
#       - ./deploy.sh

.nthlayer-gate:
  image: python:3.11-slim
  variables:
    # Required: Set these in your CI/CD variables
    # PROMETHEUS_URL: https://prometheus.example.com
    # SERVICE_FILE: services/my-service.yaml
    ENVIRONMENT: prod
  before_script:
    - pip install --quiet nthlayer
  script:
    - |
      set +e
      nthlayer check-deploy "$SERVICE_FILE" \
        --prometheus-url "$PROMETHEUS_URL" \
        --environment "$ENVIRONMENT"
      EXIT_CODE=$?
      set -e

      if [ $EXIT_CODE -eq 0 ]; then
        echo "✅ Deployment gate: APPROVED"
      elif [ $EXIT_CODE -eq 1 ]; then
        echo "⚠️  Deployment gate: WARNING - proceeding with caution"
      else
        echo "❌ Deployment gate: BLOCKED"
        exit 2
      fi

# Example job that uses the gate
.deploy-with-gate:
  extends: .nthlayer-gate
  stage: deploy
  script:
    - |
      # First run the gate check
      nthlayer check-deploy "$SERVICE_FILE" \
        --prometheus-url "$PROMETHEUS_URL" \
        --environment "$ENVIRONMENT"

      # If we get here, deploy is approved (or warning)
      echo "Proceeding with deployment..."
      # Add your deploy commands here
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

# Separate gate check job (alternative approach)
.gate-check-job:
  extends: .nthlayer-gate
  stage: .pre
  script:
    - nthlayer check-deploy "$SERVICE_FILE" --prometheus-url "$PROMETHEUS_URL"
  allow_failure: false  # Block pipeline if gate fails
