name: 'NthLayer Deployment Gate'
description: 'Check error budget before deployment'
author: 'NthLayer'

inputs:
  service-file:
    description: 'Path to service.yaml file'
    required: true
  prometheus-url:
    description: 'Prometheus server URL'
    required: true
  environment:
    description: 'Deployment environment (dev, staging, prod)'
    required: false
    default: 'prod'
  prometheus-username:
    description: 'Prometheus basic auth username (optional)'
    required: false
  prometheus-password:
    description: 'Prometheus basic auth password (optional)'
    required: false

outputs:
  result:
    description: 'Gate result (approved, warning, blocked)'
  budget-remaining:
    description: 'Error budget remaining percentage'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install NthLayer
      shell: bash
      run: pip install nthlayer

    - name: Run Deployment Gate Check
      id: gate
      shell: bash
      env:
        PROMETHEUS_URL: ${{ inputs.prometheus-url }}
        PROMETHEUS_USERNAME: ${{ inputs.prometheus-username }}
        PROMETHEUS_PASSWORD: ${{ inputs.prometheus-password }}
      run: |
        set +e
        nthlayer check-deploy ${{ inputs.service-file }} \
          --prometheus-url "$PROMETHEUS_URL" \
          --environment ${{ inputs.environment }}
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -eq 0 ]; then
          echo "result=approved" >> $GITHUB_OUTPUT
        elif [ $EXIT_CODE -eq 1 ]; then
          echo "result=warning" >> $GITHUB_OUTPUT
        else
          echo "result=blocked" >> $GITHUB_OUTPUT
          exit 2
        fi

branding:
  icon: 'shield'
  color: 'green'
