---
# NthLayer Deployment Gate - Tekton Task
#
# A reusable Tekton Task that checks error budget before deployment.
#
# Usage in a Pipeline:
#   - name: check-deployment-gate
#     taskRef:
#       name: nthlayer-deployment-gate
#     params:
#       - name: service-file
#         value: services/my-service.yaml
#       - name: prometheus-url
#         value: https://prometheus.example.com

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nthlayer-deployment-gate
  labels:
    app.kubernetes.io/name: nthlayer
    app.kubernetes.io/component: deployment-gate
spec:
  description: |
    Check error budget before deployment using NthLayer.
    Blocks deployment if error budget is exhausted.

  params:
    - name: service-file
      type: string
      description: Path to service.yaml file
    - name: prometheus-url
      type: string
      description: Prometheus server URL
    - name: environment
      type: string
      description: Deployment environment
      default: "prod"
    - name: nthlayer-version
      type: string
      description: NthLayer version to install
      default: "latest"

  results:
    - name: result
      type: string
      description: Gate result (approved, warning, blocked)
    - name: budget-remaining
      type: string
      description: Error budget remaining percentage

  steps:
    - name: check-gate
      image: python:3.11-slim
      env:
        - name: PROMETHEUS_URL
          value: "$(params.prometheus-url)"
        - name: PROMETHEUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: prometheus-credentials
              key: username
              optional: true
        - name: PROMETHEUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prometheus-credentials
              key: password
              optional: true
      script: |
        #!/bin/bash
        set -e

        # Install NthLayer
        if [ "$(params.nthlayer-version)" = "latest" ]; then
          pip install --quiet nthlayer
        else
          pip install --quiet nthlayer==$(params.nthlayer-version)
        fi

        # Run gate check
        set +e
        nthlayer check-deploy "$(params.service-file)" \
          --prometheus-url "$PROMETHEUS_URL" \
          --environment "$(params.environment)"
        EXIT_CODE=$?
        set -e

        # Write results
        if [ $EXIT_CODE -eq 0 ]; then
          echo -n "approved" | tee $(results.result.path)
        elif [ $EXIT_CODE -eq 1 ]; then
          echo -n "warning" | tee $(results.result.path)
        else
          echo -n "blocked" | tee $(results.result.path)
          echo "Deployment blocked - error budget exhausted"
          exit 2
        fi

---
# Example Pipeline using the task
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-with-gate
spec:
  params:
    - name: service-file
      type: string
    - name: prometheus-url
      type: string
    - name: environment
      type: string
      default: "prod"

  tasks:
    - name: check-gate
      taskRef:
        name: nthlayer-deployment-gate
      params:
        - name: service-file
          value: $(params.service-file)
        - name: prometheus-url
          value: $(params.prometheus-url)
        - name: environment
          value: $(params.environment)

    - name: deploy
      runAfter: [check-gate]
      taskRef:
        name: deploy-app  # Your deploy task
      when:
        - input: $(tasks.check-gate.results.result)
          operator: in
          values: ["approved", "warning"]

---
# Example PipelineRun
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: deploy-with-gate-
spec:
  pipelineRef:
    name: deploy-with-gate
  params:
    - name: service-file
      value: services/api.yaml
    - name: prometheus-url
      value: https://prometheus.internal:9090
    - name: environment
      value: prod
